project:
  type: website
  output-dir: docs

website:
  title: "Bob Prowse Health Club"
  navbar:
    background: primary
    search: true
    left:
      - text: "Coaches"
        href: coaches.qmd
      - text: "App"
        href: app.qmd
      - text: "Training"
        href: training.qmd
      - text: "Gym"
        href: gym.qmd
      - text: "Services"
        href: services.qmd
      - text: "Join"
        href: join.qmd
    tools:
      - icon: twitter
        href: https://X.com/BobProwseGym
      - icon: instagram
        href: https://www.instagram.com/bobprowsehealthclub/
      - icon: facebook
        href: https://www.facebook.com/BobProwseGym/

  
format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true



